"""add difficulty_ratio knowledge_node_ids to exam_papers

Revision ID: 98ef1419364d
Revises: 004_v4_show_units_timer
Create Date: 2026-06-02 05:36:51.568451+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98ef1419364d'
down_revision: Union[str, Sequence[str], None] = '004_v4_show_units_timer'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_answer_sub_unit', table_name='answer_submissions')
    op.create_index(op.f('ix_answer_submissions_ocr_upload_id'), 'answer_submissions', ['ocr_upload_id'], unique=False)
    op.create_index(op.f('ix_answer_submissions_unit_id'), 'answer_submissions', ['unit_id'], unique=False)
    op.drop_index('idx_upq_unit', table_name='exam_paper_unit_questions')
    op.drop_constraint('uq_unit_question', 'exam_paper_unit_questions', type_='unique')
    op.create_index(op.f('ix_exam_paper_unit_questions_unit_id'), 'exam_paper_unit_questions', ['unit_id'], unique=False)
    op.create_unique_constraint('uq_exam_paper_unit_questions', 'exam_paper_unit_questions', ['unit_id', 'question_id'])
    op.alter_column('exam_paper_units', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('exam_paper_units', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_units_paper', table_name='exam_paper_units')
    op.create_index(op.f('ix_exam_paper_units_exam_paper_id'), 'exam_paper_units', ['exam_paper_id'], unique=False)
    op.add_column('exam_papers', sa.Column('difficulty_ratio', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('exam_papers', sa.Column('knowledge_node_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index('ix_explanation_sessions_question_id', table_name='explanation_sessions')
    op.create_index(op.f('ix_explanation_sessions_question_id'), 'explanation_sessions', ['question_id'], unique=False)
    op.alter_column('provinces', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('provinces', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_explanation_sessions_question_id'), table_name='explanation_sessions')
    op.create_index('ix_explanation_sessions_question_id', 'explanation_sessions', ['question_id', 'is_active'], unique=False)
    op.drop_column('exam_papers', 'knowledge_node_ids')
    op.drop_column('exam_papers', 'difficulty_ratio')
    op.drop_index(op.f('ix_exam_paper_units_exam_paper_id'), table_name='exam_paper_units')
    op.create_index('idx_units_paper', 'exam_paper_units', ['exam_paper_id', 'position'], unique=False)
    op.alter_column('exam_paper_units', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('exam_paper_units', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_exam_paper_unit_questions', 'exam_paper_unit_questions', type_='unique')
    op.drop_index(op.f('ix_exam_paper_unit_questions_unit_id'), table_name='exam_paper_unit_questions')
    op.create_unique_constraint('uq_unit_question', 'exam_paper_unit_questions', ['unit_id', 'question_id'])
    op.create_index('idx_upq_unit', 'exam_paper_unit_questions', ['unit_id', 'position'], unique=False)
    op.drop_index(op.f('ix_answer_submissions_unit_id'), table_name='answer_submissions')
    op.drop_index(op.f('ix_answer_submissions_ocr_upload_id'), table_name='answer_submissions')
    op.create_index('idx_answer_sub_unit', 'answer_submissions', ['unit_id'], unique=False)
    # ### end Alembic commands ###
